version: '3.8'
services:
  postgresql:
    container_name: "demo"
    image: postgres:15.2-alpine
    restart: on-failure
    ports:
      - '5432:5432'
    volumes:
      - "C:/space/docker-volumes/db/demo:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo