spring.application.name=moneyminder

spring.threads.virtual.enabled=true
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/money-minder
spring.datasource.username=admin
spring.datasource.password=admin

monobank.api.url=https://api.monobank.ua